### PR TITLE
Reduce noise if a week crosses a month

### PR DESCRIPTION
**Pull request by PhyberApex**
Reworked template to not include year - quarter - month but only what changed if a week crosses a month

### CODE REVIEW

**Comment by ljavuras** [comment]
Awesome, much appreciated!

Can you push the weekly template to a separate folder, e.g. `template advanced/improved month crossing week`?

I intend to introduce other improvements, such as a fix for pitfall, better support for customized filename format & display name, etc.

I'll push them to `template advanced/` with their separate folder, to keep the basic template easy to understand and tinker with.

**Comment by ljavuras** [comment]
I have merged your PR, thanks a bunch! @PhyberApex

**Comment by PhyberApex** [comment]
No worries sorry for not responding earlier. I totally forgot a out the change you wanted :)

**Comment by ljavuras** [comment]
I'm grateful that you contributed in the first place! 

I duplicated the template and pushed your patch into one of it. Fixed an error and rearranged the comments.

Feel free to leave any comments if you have more suggestions

**Pull request merged**
